POST https://phonebook-backend-9ofx.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Agustin Mediotti",
    "number": "6181121"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Agustin Mediotti",
    "number": "6181121"
}